In [ ]:
"""
Credits: https://learningtensorflow.com
"""

In [2]:
import tensorflow as tf

In [3]:
# elementwise operation
a = tf.constant([1, 2, 3], name='a')
b = tf.constant([4, 5, 6], name='b')
add_op = a + b

with tf.Session() as session:
    print(session.run(add_op))

[5 7 9]


In [4]:
# broadcasted operation
a = tf.constant([1, 2, 3], name='a')
b = tf.constant(4, name='b')
add_op = a + b

with tf.Session() as session:
    print(session.run(add_op))

[5 6 7]


In [6]:
# elementwise operation
a = tf.constant([[1, 2, 3], [4, 5, 6]], name='a')
b = tf.constant([[1, 2, 3], [4, 5, 6]], name='b')
add_op = a + b

with tf.Session() as session:
    print(session.run(add_op))

[[ 2  4  6]
 [ 8 10 12]]


In [7]:
# broadcasted operation
a = tf.constant([[1, 2, 3], [4, 5, 6]], name='a')
b = tf.constant(100, name='b')
add_op = a + b

with tf.Session() as session:
    print(session.run(add_op))

[[101 102 103]
 [104 105 106]]


In [16]:
# b broadcasted to the shape of the matrix a
a = tf.constant([[1, 2, 3], [4, 5, 6]], name='a')
b = tf.constant([100, 101, 102], name='b')
add_op = a + b

with tf.Session() as session:
    print(session.run(add_op))

[[101 103 105]
 [104 106 108]]


In [17]:
a.shape

TensorShape([Dimension(2), Dimension(3)])

In [18]:
b.shape

TensorShape([Dimension(3)])

In [11]:
a = tf.constant([[1, 2, 3], [4, 5, 6]], name='a')
b = tf.constant([[100], [101]], name='b')
add_op = a + b

with tf.Session() as session:
    print(session.run(add_op))

[[101 102 103]
 [105 106 107]]


In [12]:
a.shape

TensorShape([Dimension(2), Dimension(3)])

In [13]:
b.shape

TensorShape([Dimension(2), Dimension(1)])