In [1]:
"""
Credits: https://learningtensorflow.com
"""

'\nCredits: https://learningtensorflow.com\n'

In [2]:
import tensorflow as tf
import numpy as np

In [5]:
x = tf.placeholder("float", None)
y = x * 2

with tf.Session() as session:
    result = session.run(y, feed_dict={x:[1, 2, 3]})
    print(result)

[ 2.  4.  6.]


In [14]:
x = tf.placeholder("float", shape=[None, 5])
y = x * 5

with tf.Session() as session:
    arr = np.random.randint(1, 50, 25).reshape((5, 5))
    print(arr)
    result = session.run(y, feed_dict={x: arr})
    print(result)

[[31 29 45 38  9]
 [43 32 10 32 14]
 [47 40 11 44 35]
 [47 19 14 22 29]
 [43 28 22 24  5]]
[[ 155.  145.  225.  190.   45.]
 [ 215.  160.   50.  160.   70.]
 [ 235.  200.   55.  220.  175.]
 [ 235.   95.   70.  110.  145.]
 [ 215.  140.  110.  120.   25.]]
